# Site settings
# These are used to personalize your new site.
title: Malik Stewart # your name here
logo: "/images/gaming_logo.png" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2021)
  <br /><br 
  <a href="https://docs.google.com/document/d/199yoFr8-r3IqW2LbnTV1-_GBFKc5Urpud7S5RtCbO34/edit?usp=sharing">View My Resume</a>
  <br /><br />
repository: "Malik526/Malik526.guthub.io"
github_username:  Malik526 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

